development:
  adapter: postgresql
  database: recipe_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: recipe_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: recipe_production
  pool: 5
